works = {
	format = "horizontal", 
	intro = {
		title = _("About Works"),		
		pt_BR = "front_page_works_pt_BR.php",		
		en_US = "front_page_works_en_US.php",		
	},		
	examples = {
		title = _("Artistas em destaque"),		
		type = "art", 
		view = "list",
		limit = 10,		
		button = {
			label = _("View all"), 
			controller = "Browse", 
			action = "works",
			}
	}	
}

artists = {
	format = "horizontal", 
	intro = {
		title = _("About Artists"),		
		pt_BR = "front_page_artists_pt_BR.php",		
		en_US = "front_page_artists_en_US.php",
	},		
	examples = {
		title = _("Artistas em destaque"),		
		type = "Artista", 
		view = "list",
		limit = 8,
		button = {
			label = _("View all"), 
			controller = "Browse", 
			action = "artists",
			}
	}
}

exhibitions = {
	format = "horizontal", 
	intro = {
		title = _("About Exhibitions"),		
		pt_BR = "front_page_exhibitions_pt_BR.php",		
		en_US = "front_page_exhibitions_en_US.php",
	},		
	examples = {
		title = _("Exposições em destaque"),		
		type = "exhibition", 
		limit = 12,		
		view = "list",
		button = {
			label = _("View all"), 
			controller = "Browse", 
			action = "exhibitions",
			}
	}
}

others = {
	groups = {
		format = "horizontal", 
		intro = {
			title = _("About Groups"),		
			pt_BR = "front_page_artists_pt_BR.php",		
			en_US = "front_page_artists_en_US.php",	
		},		
		examples = {
			title = _("Outros em destaque"),	
			table = "ca_entities", 	
			parameter = "entity_types", 
			type = "coletivo", 
			view = "list",
			limit = 8,
			button = {
				label = _("View all"), 
				controller = "Browse", 
				action = "artists",
				}
		}
	}, 
	publications = {
		format = "horizontal", 
		intro = {
			title = _("About Publications"),		
			pt_BR = "front_page_exhibitions_pt_BR.php",		
			en_US = "front_page_exhibitions_en_US.php",
		},		
		examples = {
			title = _("Publicações em destaque"),
			table = "ca_occurrences", 	
			parameter = "occurrence_types", 		
			type = "publicacao", 
			view = "list",
			limit = 8,
			button = {
				label = _("View all"), 
				controller = "Browse", 
				action = "others",
				}
		}
	}
}