
works = {
	format = "horizontal", 
	intro = {
		title = _("About Works"),		
		pt_BR = "front_page_works_pt_BR.php",		
		en_US = "front_page_works_en_US.php",
	},		
	examples = {
		title = _("Artistas em destaque"),
		limit = 8,
		view = "list",
		button = {
			label = _("View all"), 
			controller = "Browse", 
			action = "works",
			}
	}
	afiches = {
		first = {
			browser = "artworks", 
			facet = "type_facet", 
			title = _("hola"),
			visual = "blocks",
			limit = 5, 
			}
		second = {
			browser = "artworks", 
			facet = "entity_facet", 
			title = _("second"),
			visual = "carrousel",
			limit = 10,}, 
		third = {
			browser = "exhibitions", 
			facet = "decade_facet", 
			title = _("second"),
			visual = "carrousel",
			limit = 10,}
	}
}

exhibitions = {
	format = "horizontal", 
	intro = {
		title = _("About Exhibitions"),		
		pt_BR = "front_page_exhibitions_pt_BR.php",		
		en_US = "front_page_exhibitions_en_US.php",
	},		
	examples = {
		title = _("Exposições em destaque"),
		limit = 14,
		view = "list",
		button = {
			label = _("View all"), 
			controller = "Browse", 
			action = "exhibitions",
			}
	}
}

artists = {
	format = "horizontal", 
	intro = {
		title = _("About Artists"),		
		pt_BR = "front_page_artists_pt_BR.php",		
		en_US = "front_page_artists_en_US.php",
	},		
	examples = {
		title = _("Artistas em destaque"),
		limit = 12,
		view = "list",
		button = {
			label = _("View all"), 
			controller = "Browse", 
			action = "artists",
			}
	}
}
