#
# Defines searches to be executed on a "multisearch" – a search across several types of records at once
#
#
multisearchTypes = {
	works = {
		displayName = _(Works),
		table = ca_objects,
		restrictToTypes = [art],
		view = Search/ca_objects_search_subview_html.php,
		itemsPerPage = 10,
		# --- sortControlType = dropdown or list
		sortControlType = list,
		sortBy = {
			Title = ca_object_labels.name
		},
		sortDirection = {			
			Title = asc
		}
	},
	collections = {
		displayName = _(Collections),
		table = ca_collections,
		restrictToTypes = [],
		view = Search/ca_collections_search_subview_html.php,
		itemsPerPage = 10,
		# --- sortControlType = dropdown or list
		sortControlType = list,
		sortBy = {
			Name = ca_collection_labels.name
		},
		sortDirection = {
			Relevance = asc,
			Identifier = desc,
			Title = asc
		}
	},	
	artists = {
		displayName = _(Artists),
		table = ca_entities,
		restrictToTypes = [artista],
		view = Search/ca_entities_search_subview_html.php,
		itemsPerPage = 12,
		itemsPerColumn = 3,
		# --- sortControlType = dropdown or list
		sortControlType = list,
		sortBy = {
			Surname = ca_entity_labels.surname;ca_entity_labels.forename
		},
		sortDirection = {			
			Surname = asc
		},
		options = {
			selectMediaUsingRelationshipTypes = []
		}
	},
	
	groups = {
		displayName = _(Groups),
		table = ca_entities,
		restrictToTypes = [coletivo],
		view = Search/ca_entities_search_subview_html.php,
		itemsPerPage = 12,
		itemsPerColumn = 3,
		# --- sortControlType = dropdown or list
		sortControlType = list,
		sortBy = {
			Name = ca_entity_labels.surname;ca_entity_labels.forename
		},
		sortDirection = {			
			Name = asc
		},
		options = {
			selectMediaUsingRelationshipTypes = []
		}
	},

	exhibitions = {
		displayName = _(Exhibitions),
		table = ca_occurrences,
		restrictToTypes = [exhibition],
		view = Search/ca_occurrences_search_subview_html.php,
		# --- sortControlType = dropdown or list
		sortControlType = list,
		itemsPerPage = 12,
		itemsPerColumn = 3,
		
		sortBy = {
			Title = ca_occurrence_labels.name
		},
		sortDirection = {
			Relevance = asc,
			Identifier = desc,
			Title = asc
		}
	}	
}
advancedSearchTypes = {
	works = {
		displayName = _(works),
		table = ca_objects,
		restrictToTypes = [art],
		view = Search/macusp_advanced_search_ca_objects_html.php, 
		itemsPerPage = 10,
		
		sortBy = {
			Entity = ca_entity_labels.surname;ca_entity_labels.forename,
			Identifier = ca_objects.idno,
			Name = ca_object_labels.name
		}
	}
	exhibitions = {
		displayName = _(Exhibitions),
		table = ca_occurrences,
		restrictToTypes = [exhibition],
		view = Search/macusp_advanced_search_ca_occurrences_exhibitions_html.php, 
		itemsPerPage = 10,
		
		sortBy = {
			Entity = ca_entity_labels.surname;ca_entity_labels.forename,
			Identifier = ca_objects.idno,
			Name = ca_object_labels.name
		}
	}
	artists = {
		displayName = _(Artists),
		table = ca_entities,
		restrictToTypes = [artista],
		view = Search/macusp_advanced_search_ca_artists_html.php, 
		itemsPerPage = 10,
		
		sortBy = {
			Entity = ca_entity_labels.surname;ca_entity_labels.forename,
			Identifier = ca_objects.idno,
			Name = ca_object_labels.name
		}
	}
	groups = {
		displayName = _(Artists),
		table = ca_entities,
		restrictToTypes = [coletivo],
		view = Search/macusp_advanced_search_ca_artists_html.php, 
		itemsPerPage = 10,
		
		sortBy = {
			Name = ca_object_labels.name
		}
		sortDirection = {			
			Name = asc
		}
	}
}
views = {
	images = {
		icon = glyphicon-th
	},
	list = {
		icon = glyphicon-list
	},
	timeline = {
		icon = glyphicon-time
	},
	map = {
		icon = glyphicon-globe
	}
}

#
# Other options
#

# default number of results per page/ajax load
defaultHitsPerBlock = 36

# add a wildcard "*" to the end of all searches? 
matchOnStem = 0
